# Based on https://github.com/PrakashTrove/AWS-CodeBuild-NetCore/blob/master/buildspec.yml
# AWS CodeBuild spec to build an Elastic Beanstalk artifact for AWS CodePipeline to deploy
version: 0.2

#env:
# secrets-manager:
#   key: "myfirstsecret:test"
  
phases:

  pre_build:
    commands:
      - echo Show time bitches! 
      
  build:
    commands:
      - aws cloudformation package --template-file s3.yaml --output-template-file s3-out.yaml --s3-bucket your-s3-bucket

artifacts:
  files:
    - s3.yaml
    - s3-out.yaml
